server:
    port: 8085

spring:
  application:
    name: gateway-service

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/spring-microservices-realm

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
#      defaultZone: http://localhost:8084/eureka/
       defaultZone: http://eureka:password@localhost:8084/eureka