server:
    port: 8087

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
#      defaultZone: http://localhost:8084/eureka/
       defaultZone: http://eureka:password@localhost:8084/eureka

