server:
    port: 8083

spring:
  application:
    name: qualification-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservice_qualification

  config:
    import: optional:configserver:http://localhost:8086