server:
  port: 8084

spring:
  application:
    name: server-service

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8084/eureka/

app:
  eureka:
    username: eureka
    password: password